<a href="https://colab.research.google.com/github/isaidaiman111/CSE311/blob/main/Copy_of_NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Assignment
These assignments involve common tasks encountered in data analysis, finance, and image processing, where NumPy can be applied to efficiently manipulate and analyze data. They require intermediate knowledge of NumPy functions such as sum, mean, nanmean, std, reshape, and dot product, among others.

Remember to consult the NumPy documentation and other resources for detailed explanations of the functions and concepts involved in these assignments.

### Assignment 1: Sales Analysis
You are given an array representing the daily sales of a product for a week. Your task is to find the total sales for the week and calculate the average daily sales.

**Data:** An array representing the daily sales of a product for a week.

```python
sales = np.array([50, 45, 55, 60, 48, 52, 58])
```

In [ ]:
import numpy as np

sales = np.array([50, 45, 55, 60, 48, 52, 58])

total_sales = np.sum(sales)
average_sales = np.mean(sales)

print("Total Sales for the Week:", total_sales)
print("Average Daily Sales:", average_sales)


### Assignment 2: Data Cleaning
You have a dataset containing customer ratings for various products. However, some ratings are missing **`(NaN values)`**. Your task is to replace all the missing ratings with the mean rating for each product.

**Data:** A dataset containing customer ratings for various products with missing values (NaN).

```python
ratings = np.array([3.5, 4.2, 2.8, np.nan, 3.9, np.nan, 4.5, 3.2, 3.7])
```

In [ ]:
import numpy as np

ratings = np.array([3.5, 4.2, 2.8, np.nan, 3.9, np.nan, 4.5, 3.2, 3.7])


mean_rating = np.nanmean(ratings)
ratings[np.isnan(ratings)] = mean_rating

print("Cleaned Ratings:", ratings)


### Assignment 3: Image Processing
You are working on an image processing project and need to apply a grayscale filter to an RGB image. Convert the RGB image into a grayscale image using numpy arrays and the appropriate color channel weights **`(e.g., 0.2989 * Red + 0.5870 * Green + 0.1140 * Blue)`**.

**Data:** An RGB image represented as a 3D numpy array with shape **`(height, width, 3)`**, where the third dimension represents the Red, Green, and Blue color channels.

```python
image = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                  [[127, 127, 127], [255, 255, 255], [0, 0, 0]],
                  [[100, 200, 50], [150, 75, 200], [25, 125, 75]]], dtype=np.uint8)
```

**`Output will be:`**
```lua
[[  76.197  76.197  76.197]
 [ 166.595 166.595 166.595]
 [ 148.293 148.293 148.293]]
 ```

In [ ]:
import numpy as np

image = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                  [[127, 127, 127], [255, 255, 255], [0, 0, 0]],
                  [[100, 200, 50], [150, 75, 200], [25, 125, 75]]], dtype=np.uint8)

weights = [0.2989, 0.5870, 0.1140]
grayscale_image = np.dot(image, weights)

print(grayscale_image)


### Assignment 4: Images Data Manupulation
You are given an image of shape **`(1000,667,3)`**. Perform the following task:
   - convert the images to a numpy array
   - Expand the dimension of image array to **`(1,1000,67,3,1)`**
   - Remove all single dimensions from the numpy array     
##### Load Image
```python
from PIL import Image
image1 = Image.open("images/cat.jpg")
```

In [ ]:
from PIL import Image
import numpy as np

image1 = Image.open("images/cat.jpg")
image_array = np.array(image1)

expanded_image = np.expand_dims(image_array, axis=(0, 4))

final_image = np.squeeze(expanded_image)

print("Image Shape:", final_image.shape)
